name: 'dailyleaderboards'
version: 0.1
main: com.github.kevindagame.DailyLeaderBoards
api-version: 1.16
author: KevinDaGame
description: new leaderboard every day!
depend: [PlaceholderAPI]
permissions:
  dailyleaderboards.*:
    description: All permissions
    default: op
    children:
      dailyleaderboards.help:
        description: Get help for the plugin

commands:
  dailyleaderboards:
    aliases: [dlb]
